name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    # Настраиваем Docker в самом Гитхабе
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Проверяем твой docker-compose.yml на ошибки
    - name: Test Docker Compose Configuration
      run: |
        docker compose config

    # Запускаем deploy.sh на удаленном сервере облака
    - name: Deploy to Cloud Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/myprojects/DevOps_Journey./Python_DevOps_Projects
          git pull origin main
          chmod +x deploy.sh
          ./deploy.sh
